Repository IBM-Blockchain/blockchain-vscode-extension, pull requests merged in 2020-06, with the labels that each got.

#2410 New cucumber software ops tools info
  azure-templates/cucumber-steps.yml
  packages/blockchain-extension/cucumber/features/fabric-environments.feature
  packages/blockchain-extension/cucumber/features/submit.feature
Labels: ignore-v2

#2401 Set collection on deploy (close #1921)
  packages/blockchain-extension/extension/webview/DeployView.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/webview/DeployView.test.ts
  packages/blockchain-ui/enzyme/tests/DeployPage.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepTwo.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepTwo.test.tsx.snap
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepTwo/DeployStepTwo.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.tsx
  packages/blockchain-ui/src/react-app-env.d.ts
Labels: v2 pr

#2420 Fixed resizing issue in tutorial gallery (bp #2411)
  packages/blockchain-ui/enzyme/tests/__snapshots__/TutorialPage.test.tsx.snap
  packages/blockchain-ui/src/components/elements/TutorialTile/TutorialTile.scss
  packages/blockchain-ui/src/components/pages/TutorialPage/TutorialPage.tsx
Labels: v2 pr

#2422 Ignore errors calling focusFilesExplorer when creating a new project …
  packages/blockchain-extension/extension/commands/createSmartContractProjectCommand.ts
  packages/blockchain-extension/test/commands/createSmartContractProjectCommand.test.ts
Labels: che

#2423 Add discovery to commit step
  packages/blockchain-fabric-admin/cucumber/features/discover.feature
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/commit.steps.ts
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/package.steps.ts
  packages/blockchain-fabric-admin/cucumber/helpers/DiscoverHelper.ts
  packages/blockchain-fabric-admin/package.json
  packages/blockchain-fabric-admin/src/Lifecycle.ts
  packages/blockchain-fabric-admin/src/LifecycleChannel.ts
  packages/blockchain-fabric-admin/test/Lifecycle.test.ts
  packages/blockchain-fabric-admin/test/LifecycleChannel.test.ts
Labels: v2 pr

#2418 Contract name already exists warning (close #2304)
  packages/blockchain-extension/extension/commands/openDeployView.ts
  packages/blockchain-extension/test/commands/openDeployView.test.ts
  packages/blockchain-ui/cypress/integration/deploy_page.spec.ts
  packages/blockchain-ui/enzyme/tests/App.test.tsx
  packages/blockchain-ui/enzyme/tests/DeployPage.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepTwo.test.tsx
  packages/blockchain-ui/src/App.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepTwo/DeployStepTwo.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.tsx
Labels: v2 pr

#2432 Added exportAppData command to allow users to export client app data (bp#2323)
  packages/blockchain-common/src/interfaces/IFabricWallet.ts
  packages/blockchain-common/test/environments/MicrofabEnvironment.test.ts
  packages/blockchain-extension/ExtensionCommands.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/commands/deployCommand.ts
  packages/blockchain-extension/extension/commands/exportAppData.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/util/FeatureFlags.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/exportAppData.test.ts
  packages/blockchain-extension/test/commands/exportConnectionProfileCommand.test.ts
  packages/blockchain-extension/test/commands/manageFeatureFlags.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-extension/test/util/FeatureFlags.test.ts
  packages/blockchain-wallet/src/FabricWallet.ts
  packages/blockchain-wallet/test/FabricWallet.test.ts
Labels: v2 pr

#2434 Changelog (v2)
  CHANGELOG.md
  packages/blockchain-extension/RELEASE-NOTES.md
Labels: v2 pr

#2437 Remove all the old code
  packages/blockchain-fabric-admin/package.json
  packages/blockchain-fabric-admin/src/old-code/CollectionConfig.ts
  packages/blockchain-fabric-admin/src/old-code/Package.ts
  packages/blockchain-fabric-admin/src/old-code/Packager.ts
  packages/blockchain-fabric-admin/src/old-code/Policy.ts
  packages/blockchain-fabric-admin/src/old-code/approvedchaincode.ts
  packages/blockchain-fabric-admin/src/old-code/chaincodepackage.ts
  packages/blockchain-fabric-admin/src/old-code/chaincodesource.ts
  packages/blockchain-fabric-admin/src/old-code/chaincodeutils.ts
  packages/blockchain-fabric-admin/src/old-code/installedchaincode.ts
  packages/blockchain-fabric-admin/src/old-code/lifecycle.ts
  packages/blockchain-fabric-admin/tsconfig.json
Labels: v2 pr

#2440 Pass endorsement policy (close #1920)
  packages/blockchain-extension/extension/webview/DeployView.ts
  packages/blockchain-extension/test/webview/DeployView.test.ts
  packages/blockchain-ui/cypress/integration/deploy_page.spec.ts
  packages/blockchain-ui/enzyme/tests/DeployPage.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepTwo.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepTwo.test.tsx.snap
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepTwo/DeployStepTwo.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.tsx
Labels: v2 pr

#2428 Update samples to use v2 version
  packages/blockchain-extension/repositories.json
  packages/blockchain-extension/test/webview/SampleView.test.ts
Labels: v2 pr

#2419 Make go module projects work on v2
  packages/blockchain-extension/cucumber/features/create.feature
  packages/blockchain-extension/cucumber/features/deploy.feature
  packages/blockchain-extension/cucumber/features/evaluate.feature
  packages/blockchain-extension/cucumber/features/fabcar-sample.feature
  packages/blockchain-extension/cucumber/features/package.feature
  packages/blockchain-extension/cucumber/features/submit.feature
  packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/packageSmartContractCommand.test.ts
  packages/blockchain-fabric-admin/src/SmartContractPackage.ts
  packages/blockchain-fabric-admin/test/SmartContractPackage.test.ts
Labels: v2 pr

#2451 Fixed bug where users werent able to package smart contracts on 1.44.2 (bp#2448)
  packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts
  packages/blockchain-extension/test/commands/packageSmartContractCommand.test.ts
Labels: v2 pr

#2458 Updated to change generator version
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
Labels: ignore-v2

#2459 Updated to change generator version on v2
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
Labels: v2 pr

#2457 Changed functions so we use the user set timeouts instead of hardcoding
  packages/blockchain-common/src/interfaces/IFabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/src/FabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/test/FabricEnvironmentConnection.test.ts
  packages/blockchain-extension/extension/commands/approveCommand.ts
  packages/blockchain-extension/extension/commands/commitCommand.ts
  packages/blockchain-extension/extension/commands/installCommand.ts
  packages/blockchain-extension/test/commands/approveCommand.test.ts
  packages/blockchain-extension/test/commands/commitCommand.test.ts
  packages/blockchain-extension/test/commands/installCommand.test.ts
Labels: v2 pr

#2454 Peer targeting (close #2229)
  packages/blockchain-common/src/interfaces/IFabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/src/FabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/test/FabricEnvironmentConnection.test.ts
  packages/blockchain-extension/extension/commands/deployCommand.ts
  packages/blockchain-extension/extension/commands/openDeployView.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/webview/DeployView.ts
  packages/blockchain-extension/test/commands/deployCommand.test.ts
  packages/blockchain-extension/test/commands/openDeployView.test.ts
  packages/blockchain-extension/test/webview/DeployView.test.ts
  packages/blockchain-fabric-admin/cucumber/features/discover.feature
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/discover.steps.ts
  packages/blockchain-fabric-admin/src/LifecycleChannel.ts
  packages/blockchain-fabric-admin/test/LifecycleChannel.test.ts
  packages/blockchain-ui/cypress/integration/deploy_page.spec.ts
  packages/blockchain-ui/enzyme/tests/App.test.tsx
  packages/blockchain-ui/enzyme/tests/DeployPage.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepThree.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepThree.test.tsx.snap
  packages/blockchain-ui/src/App.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepThree/DeployStepThree.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.tsx
Labels: v2 pr

#2466 Changelog
  CHANGELOG.md
  packages/blockchain-extension/RELEASE-NOTES.md
Labels: ignore-v2

#2467 Changelog (v2)
  CHANGELOG.md
  packages/blockchain-extension/RELEASE-NOTES.md
Labels: v2 pr

#2479 SDK Fix (v2)
  CHANGELOG.md
  packages/blockchain-environment-v1/package-lock.json
  packages/blockchain-environment-v1/package.json
  packages/blockchain-extension/RELEASE-NOTES.md
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-extension/patches/fabric-network+2.1.1-snapshot.374.patch
  packages/blockchain-fabric-admin/package-lock.json
  packages/blockchain-fabric-admin/package.json
  packages/blockchain-fabric-admin/patches/fabric-network+2.1.1-snapshot.374.patch
  packages/blockchain-fabric-admin/src/LifecyclePeer.ts
  packages/blockchain-fabric-admin/test/LifecycleChannel.test.ts
  packages/blockchain-gateway-v1/package-lock.json
  packages/blockchain-gateway-v1/package.json
  packages/blockchain-gateway-v1/src/FabricConnection.ts
  packages/blockchain-gateway-v1/src/FabricGatewayConnection.ts
  packages/blockchain-gateway-v1/test/FabricConnection.test.ts
  packages/blockchain-gateway-v1/test/FabricGatewayConnection.test.ts
  packages/blockchain-wallet/package-lock.json
  packages/blockchain-wallet/package.json
Labels: v2 pr

#2473 Organisation approval table (close #2436)
  packages/blockchain-common/src/interfaces/IFabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/package-lock.json
  packages/blockchain-environment-v1/src/FabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/test/FabricEnvironmentConnection.test.ts
  packages/blockchain-extension/extension/commands/openDeployView.ts
  packages/blockchain-extension/extension/webview/DeployView.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/openDeployView.test.ts
  packages/blockchain-extension/test/webview/DeployView.test.ts
  packages/blockchain-fabric-admin/src/LifecycleChannel.ts
  packages/blockchain-gateway-v1/package-lock.json
  packages/blockchain-ui/cypress/integration/deploy_page.spec.ts
  packages/blockchain-ui/enzyme/tests/App.test.tsx
  packages/blockchain-ui/enzyme/tests/DeployPage.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepThree.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepTwo.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepThree.test.tsx.snap
  packages/blockchain-ui/src/App.tsx
  packages/blockchain-ui/src/Utils.ts
  packages/blockchain-ui/src/components/elements/CommandTile/CommandTile.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepThree/DeployStepThree.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepTwo/DeployStepTwo.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.tsx
  packages/blockchain-wallet/package-lock.json
Labels: v2 pr
