Repository IBM-Blockchain/blockchain-vscode-extension, pull requests merged in 2020-12, with the labels that each got.

#2836 Fixed exporting cds packages (close #2836)
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/commands/exportSmartContractPackageCommand.ts
  packages/blockchain-extension/test/commands/UserInputUtil.test.ts
  packages/blockchain-extension/test/commands/exportSmartContractPackageCommand.test.ts
  packages/blockchain-extension/test/data/packageDir/v2/packages/mypackage@0.0.1.cds
  packages/blockchain-extension/test/explorer/packageExplorer.test.ts
  packages/blockchain-extension/test/registries/PackageRegistry.test.ts
Labels: merge-2648 pr

#2837 Complete TypeScript contract types (close #2766)
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
Labels: merge-2648 pr

#2812 Update Transaction view smart contract on a contract update
  packages/blockchain-extension/extension/commands/deployCommand.ts
  packages/blockchain-extension/extension/commands/openTransactionViewCommand.ts
  packages/blockchain-extension/extension/fabric/FabricGatewayConnectionManager.ts
  packages/blockchain-extension/extension/interfaces/ISmartContract.ts
  packages/blockchain-extension/extension/webview/TransactionView.ts
  packages/blockchain-extension/test/commands/deployCommand.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-extension/test/webview/TransactionView.test.ts
  packages/blockchain-ui/enzyme/tests/TransactionInputContainer.test.tsx
  packages/blockchain-ui/enzyme/tests/TransactionPage.test.tsx
  packages/blockchain-ui/src/components/elements/TransactionInputContainer/TransactionInputContainer.tsx
  packages/blockchain-ui/src/components/elements/TransactionManualInput/TransactionManualInput.tsx
  packages/blockchain-ui/src/components/pages/TransactionPage/TransactionPage.tsx
Labels: v2 pr

#2845 Update Transaction view smart contract on a contract update (Merge for #2812)
  packages/blockchain-extension/extension/commands/deployCommand.ts
  packages/blockchain-extension/extension/commands/openTransactionViewCommand.ts
  packages/blockchain-extension/extension/fabric/FabricGatewayConnectionManager.ts
  packages/blockchain-extension/extension/interfaces/ISmartContract.ts
  packages/blockchain-extension/extension/webview/TransactionView.ts
  packages/blockchain-extension/test/commands/deployCommand.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-extension/test/webview/TransactionView.test.ts
  packages/blockchain-ui/enzyme/tests/TransactionInputContainer.test.tsx
  packages/blockchain-ui/enzyme/tests/TransactionPage.test.tsx
  packages/blockchain-ui/src/components/elements/TransactionInputContainer/TransactionInputContainer.tsx
  packages/blockchain-ui/src/components/elements/TransactionManualInput/TransactionManualInput.tsx
  packages/blockchain-ui/src/components/pages/TransactionPage/TransactionPage.tsx
Labels: ignore-v2, merge-2648 pr

#2844 Stop old style txdata file selection from showing when using Transaction View
  packages/blockchain-extension/extension/commands/submitTransaction.ts
  packages/blockchain-extension/test/commands/submitTransaction.test.ts
Labels: merge-2648 pr

#2840 [merge] read name and version for v1 contracts from package file
  packages/blockchain-environment-v1/src/PackageSmartContract.ts
  packages/blockchain-environment-v1/test/PackageSmartContract.test.ts
  packages/blockchain-extension/cucumber/features/package.feature
  packages/blockchain-extension/extension/commands/exportSmartContractPackageCommand.ts
  packages/blockchain-extension/extension/explorer/model/PackageTreeItem.ts
  packages/blockchain-extension/extension/explorer/packageExplorer.ts
  packages/blockchain-extension/extension/registries/PackageRegistry.ts
  packages/blockchain-extension/test/data/packageDir/v2/packages/fabcar-typescript.cds
  packages/blockchain-extension/test/explorer/packageExplorer.test.ts
  packages/blockchain-extension/test/registries/PackageRegistry.test.ts
  packages/blockchain-fabric-admin/src/V1SmartContractPackage.ts
  packages/blockchain-fabric-admin/test/SmartContractPackage.test.ts
Labels: merge-2648 pr

#2846 Sample gallery (close #2838)
  packages/blockchain-extension/ExtensionCommands.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/webview/SampleGalleryView.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/repositories.json
  packages/blockchain-extension/templates/SampleView.ejs
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-extension/test/webview/SampleGalleryView.test.ts
  packages/blockchain-ui/cypress/integration/tutorial_page.spec.ts
  packages/blockchain-ui/enzyme/tests/App.test.tsx
  packages/blockchain-ui/enzyme/tests/SampleGalleryPage.test.tsx
  packages/blockchain-ui/enzyme/tests/SampleTabs.test.tsx
  packages/blockchain-ui/enzyme/tests/SampleTile.test.tsx
  packages/blockchain-ui/enzyme/tests/TutorialGalleryPage.test.tsx
  packages/blockchain-ui/enzyme/tests/__snapshots__/HomePage.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/SampleGalleryPage.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/SampleTabs.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/SampleTile.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/TutorialGalleryPage.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/TutorialTabs.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/TutorialTile.test.tsx.snap
  packages/blockchain-ui/src/App.scss
  packages/blockchain-ui/src/App.tsx
  packages/blockchain-ui/src/components/elements/SampleTabs/SampleTabs.scss
  packages/blockchain-ui/src/components/elements/SampleTabs/SampleTabs.tsx
  packages/blockchain-ui/src/components/elements/SampleTile/SampleTile.tsx
  packages/blockchain-ui/src/components/elements/TutorialTabs/TutorialTabs.tsx
  packages/blockchain-ui/src/components/elements/TutorialTile/TutorialTile.scss
  packages/blockchain-ui/src/components/elements/TutorialTile/TutorialTile.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.scss
  packages/blockchain-ui/src/components/pages/HomePage/HomePage.scss
  packages/blockchain-ui/src/components/pages/HomePage/HomePage.tsx
  packages/blockchain-ui/src/components/pages/SampleGalleryPage/SampleGalleryPage.tsx
  packages/blockchain-ui/src/components/pages/TransactionPage/TransactionPage.scss
  packages/blockchain-ui/src/components/pages/TutorialGalleryPage/TutorialGalleryPage.scss
  packages/blockchain-ui/src/components/pages/TutorialGalleryPage/TutorialGalleryPage.tsx
  packages/blockchain-ui/src/index.scss
  packages/blockchain-ui/src/interfaces/ICategoryObject.ts
  packages/blockchain-ui/src/interfaces/IRepositoryObject.ts
  packages/blockchain-ui/src/interfaces/ISampleObject.ts
  packages/blockchain-ui/src/styles/gallery.scss
  packages/blockchain-ui/src/styles/mixins/layout-mixins.scss
  packages/blockchain-ui/src/styles/mixins/theme-mixins.scss
  packages/test/tmp/v2/environments/1 Org Local Fabric/.config.json
Labels: merge-2648 pr

#2847 Add ability to change smartContract/transaction while the Transaction View is open
  packages/blockchain-extension/extension/webview/TransactionView.ts
  packages/blockchain-extension/test/webview/TransactionView.test.ts
  packages/blockchain-ui/enzyme/tests/TransactionInputContainer.test.tsx
  packages/blockchain-ui/src/App.tsx
  packages/blockchain-ui/src/components/elements/TransactionInputContainer/TransactionInputContainer.tsx
Labels: merge-2648 pr

#2850 [merge] transaction view without metadata - 2.1
  packages/blockchain-extension/extension/commands/openTransactionViewCommand.ts
  packages/blockchain-extension/extension/util/MetadataUtil.ts
  packages/blockchain-extension/test/commands/openTransactionViewCommand.test.ts
  packages/blockchain-extension/test/util/MetadataUtil.test.ts
  packages/blockchain-ui/enzyme/tests/TransactionInputContainer.test.tsx
  packages/blockchain-ui/enzyme/tests/__snapshots__/TransactionInputContainer.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/TransactionPage.test.tsx.snap
  packages/blockchain-ui/src/components/elements/TransactionInputContainer/TransactionInputContainer.tsx
  packages/blockchain-ui/src/components/elements/TransactionManualInput/TransactionManualInput.tsx
  packages/blockchain-ui/src/interfaces/ISmartContract.ts
Labels: merge-2648 pr

#2851 [merge] allow import of v1 and v2 package with same name and version
  packages/blockchain-extension/extension/commands/importSmartContractPackageCommand.ts
  packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts
  packages/blockchain-extension/test/commands/importSmartContractPackageCommand.test.ts
  packages/blockchain-extension/test/commands/packageSmartContractCommand.test.ts
Labels: merge-2648 pr

#2859 Remove contract version selection
  packages/blockchain-extension/cucumber/features/create.feature
  packages/blockchain-extension/cucumber/features/deploy.feature
  packages/blockchain-extension/cucumber/features/evaluate.feature
  packages/blockchain-extension/cucumber/features/fabcar-sample.feature
  packages/blockchain-extension/cucumber/features/fabric-environments.feature
  packages/blockchain-extension/cucumber/features/fabric-gateways.feature
  packages/blockchain-extension/cucumber/features/package.feature
  packages/blockchain-extension/cucumber/features/submit.feature
  packages/blockchain-extension/cucumber/features/upgrade.feature
  packages/blockchain-extension/cucumber/helpers/smartContractHelper.ts
  packages/blockchain-extension/cucumber/steps/package.steps.ts
  packages/blockchain-extension/cucumber/steps/smartContract.steps.ts
  packages/blockchain-extension/extension/commands/createSmartContractProjectCommand.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/createSmartContractProjectCommand.test.ts
  packages/blockchain-fabric-admin/cucumber/features/approve.feature
  packages/blockchain-fabric-admin/cucumber/features/commit.feature
  packages/blockchain-fabric-admin/cucumber/features/discover.feature
  packages/blockchain-fabric-admin/cucumber/features/install.feature
  packages/blockchain-fabric-admin/cucumber/features/package.feature
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/package.steps.ts
  packages/blockchain-fabric-admin/cucumber/helpers/PackageHelper.ts
Labels: merge-2648 pr

#2857 Refactor transaction arguments to validate instead of force JSON
  packages/blockchain-ui/enzyme/tests/TransactionInputContainer.test.tsx
  packages/blockchain-ui/src/components/elements/TransactionInputContainer/TransactionInputContainer.tsx
  packages/blockchain-ui/src/components/elements/TransactionManualInput/TransactionManualInput.scss
  packages/blockchain-ui/src/components/elements/TransactionManualInput/TransactionManualInput.tsx
  packages/blockchain-ui/src/interfaces/ITransactionManualInput.ts
Labels: merge-2648 pr

#2855 Tutorial updates
  README.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a3.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a6.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a7.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a9.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a3.10.1.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a3.10.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a3.5.1.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a3.6.1.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a3.6.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a3.7.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a3.8.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a3.9.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a6.10.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a6.11.2.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a6.11.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a8.2.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a9.7.1.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a9.7.2.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a9.7.3.png
  packages/blockchain-ui/enzyme/tests/__snapshots__/Fabric2Page.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/HomePage.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/TutorialSinglePage.test.tsx.snap
  packages/blockchain-ui/src/components/elements/TransactionDataInput/TransactionDataInput.tsx
  packages/blockchain-ui/src/components/elements/TutorialMarkdown/TutorialMarkdown.tsx
  packages/blockchain-ui/src/components/pages/Fabric2Page/Fabric2Page.tsx
  packages/blockchain-ui/src/components/pages/HomePage/HomePage.tsx
Labels: do not merge, merge-2648 pr

#2860 Updated deploy view to install + instantiate V1 contracts
  packages/blockchain-extension/extension/commands/importSmartContractPackageCommand.ts
  packages/blockchain-extension/extension/commands/installCommand.ts
  packages/blockchain-extension/extension/commands/instantiateCommand.ts
  packages/blockchain-extension/extension/commands/openDeployView.ts
  packages/blockchain-extension/extension/commands/upgradeCommand.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/webview/DeployView.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/importSmartContractPackageCommand.test.ts
  packages/blockchain-extension/test/commands/installCommand.test.ts
  packages/blockchain-extension/test/commands/instantiateCommand.test.ts
  packages/blockchain-extension/test/commands/openDeployView.test.ts
  packages/blockchain-extension/test/commands/upgradeCommand.test.ts
  packages/blockchain-extension/test/webview/DeployView.test.ts
  packages/blockchain-ui/cypress/integration/deploy_page.spec.ts
  packages/blockchain-ui/enzyme/tests/DeployExplanation.test.tsx
  packages/blockchain-ui/enzyme/tests/DeployOrgApprovalTable.test.tsx
  packages/blockchain-ui/enzyme/tests/DeployPage.test.tsx
  packages/blockchain-ui/enzyme/tests/DeployProgressBar.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepOne.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepThree.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepTwo.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepThree.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepTwo.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/DeployExplanation.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/DeployOrgApprovalTable.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/DeployProgressBar.test.tsx.snap
  packages/blockchain-ui/src/App.tsx
  packages/blockchain-ui/src/Utils.ts
  packages/blockchain-ui/src/components/elements/DeployExplanation/DeployExplanation.scss
  packages/blockchain-ui/src/components/elements/DeployExplanation/DeployExplanation.tsx
  packages/blockchain-ui/src/components/elements/DeployOrgApprovalTable/DeployOrgApprovalTable.tsx
  packages/blockchain-ui/src/components/elements/DeployProgressBar/DeployProgressBar.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepOne/DeployStepOne.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepThree/DeployStepThree.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepTwo/DeployStepTwo.scss
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepTwo/DeployStepTwo.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.tsx
  packages/blockchain-ui/src/index.scss
  packages/blockchain-ui/src/styles/mixins/theme-mixins.scss
Labels: merge-2648 pr

#2864 OpenSSL update & learn more message on upgrade
  packages/blockchain-extension/extension/dependencies/Dependencies.ts
  packages/blockchain-extension/extension/dependencies/DependencyManager.ts
  packages/blockchain-extension/extension/extension.ts
  packages/blockchain-extension/test/TestUtil.ts
  packages/blockchain-extension/test/dependencies/DependencyManager.test.ts
  packages/blockchain-extension/test/extension.test.ts
  packages/blockchain-extension/test/webview/PreReqView.test.ts
  packages/blockchain-ui/enzyme/tests/__snapshots__/Fabric2Page.test.tsx.snap
  packages/blockchain-ui/src/components/pages/Fabric2Page/Fabric2Page.tsx
Labels: merge-2648 pr

#2866 [merge] fix go contracts cds packaging
  packages/blockchain-extension/cucumber/features/package.feature
  packages/blockchain-extension/cucumber/steps/package.steps.ts
  packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts
  packages/blockchain-extension/test/commands/packageSmartContractCommand.test.ts
  packages/blockchain-fabric-admin/cucumber/features/package.feature
  packages/blockchain-fabric-admin/cucumber/helpers/PackageHelper.ts
  packages/blockchain-fabric-admin/cucumber/setup-tests.sh
  packages/blockchain-fabric-admin/src/V1SmartContractPackage.ts
  packages/blockchain-fabric-admin/src/V2SmartContractPackage.ts
  packages/blockchain-fabric-admin/src/packager/BasePackager.ts
  packages/blockchain-fabric-admin/src/packager/Golang.ts
  packages/blockchain-fabric-admin/test/SmartContractPackage.test.ts
  packages/blockchain-fabric-admin/test/data/golang-gopath/src/fab-car-mod/fabcar.go
  packages/blockchain-fabric-admin/test/data/golang-gopath/src/fab-car-mod/go.mod
  packages/blockchain-fabric-admin/test/data/golang-gopath/src/fab-car-mod/go.sum
  packages/blockchain-fabric-admin/test/data/golang-gopath/src/fab-car/fabcar.go
  packages/blockchain-fabric-admin/test/data/golang-gopath/src/fab-car/go.sum
Labels: merge-2648 pr

#2863 Changelog & version update
  CHANGELOG.md
  lerna.json
  packages/blockchain-common/package-lock.json
  packages/blockchain-common/package.json
  packages/blockchain-common/test/data/otherLocalEnv/is_generated.sh
  packages/blockchain-common/test/data/otherLocalEnv/is_running.sh
  packages/blockchain-common/test/data/otherLocalEnv/start.cmd
  packages/blockchain-common/test/data/otherLocalEnv/start.sh
  packages/blockchain-common/test/data/otherLocalEnv/stop.sh
  packages/blockchain-common/test/data/otherLocalEnv/teardown.sh
  packages/blockchain-environment-v1/package-lock.json
  packages/blockchain-environment-v1/package.json
  packages/blockchain-extension/RELEASE-NOTES.md
  packages/blockchain-extension/extension/extension.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/data/1 Org Local Fabric/is_generated.sh
  packages/blockchain-extension/test/data/1 Org Local Fabric/is_running.sh
  packages/blockchain-extension/test/data/1 Org Local Fabric/start.cmd
  packages/blockchain-extension/test/data/1 Org Local Fabric/start.sh
  packages/blockchain-extension/test/data/1 Org Local Fabric/stop.sh
  packages/blockchain-extension/test/data/1 Org Local Fabric/teardown.sh
  packages/blockchain-extension/test/data/OtherLocalMicrofab/is_generated.sh
  packages/blockchain-extension/test/data/OtherLocalMicrofab/is_running.sh
  packages/blockchain-extension/test/data/OtherLocalMicrofab/start.cmd
  packages/blockchain-extension/test/data/OtherLocalMicrofab/start.sh
  packages/blockchain-extension/test/data/OtherLocalMicrofab/stop.sh
  packages/blockchain-extension/test/data/OtherLocalMicrofab/teardown.sh
  packages/blockchain-fabric-admin/package-lock.json
  packages/blockchain-fabric-admin/package.json
  packages/blockchain-gateway-v1/package-lock.json
  packages/blockchain-gateway-v1/package.json
  packages/blockchain-ui/package-lock.json
  packages/blockchain-ui/package.json
  packages/blockchain-wallet/package-lock.json
  packages/blockchain-wallet/package.json
  packages/blockchain-website/package-lock.json
  packages/blockchain-website/package.json
  test/data/1 Org Local Fabric/is_generated.sh
  test/data/1 Org Local Fabric/is_running.sh
  test/data/1 Org Local Fabric/start.cmd
  test/data/1 Org Local Fabric/start.sh
  test/data/1 Org Local Fabric/stop.sh
  test/data/1 Org Local Fabric/teardown.sh
Labels: merge-2648 pr

#2868 [merge] fix finding bad extension packages
  packages/blockchain-extension/extension/registries/PackageRegistry.ts
  packages/blockchain-extension/test/data/badPackageDir/v2/packages/fabcar-typescript@0.0.2.tgz.bad
  packages/blockchain-extension/test/data/badPackageDir/v2/packages/mypackage@0.0.1.cds.bad
Labels: merge-2648 pr

#2870 Remove docker compose dependency (close #2506)
  README.md
  packages/blockchain-extension/extension/dependencies/Dependencies.ts
  packages/blockchain-extension/extension/dependencies/DependencyManager.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/templates/PreReqView.ejs
  packages/blockchain-extension/test/dependencies/DependencyManager.test.ts
  packages/blockchain-extension/test/webview/PreReqView.test.ts
Labels: merge-2648 pr

#2875 Version update (RC1)
  CHANGELOG.md
  lerna.json
  packages/blockchain-common/package-lock.json
  packages/blockchain-common/package.json
  packages/blockchain-environment-v1/package-lock.json
  packages/blockchain-environment-v1/package.json
  packages/blockchain-extension/RELEASE-NOTES.md
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-fabric-admin/package-lock.json
  packages/blockchain-fabric-admin/package.json
  packages/blockchain-gateway-v1/package-lock.json
  packages/blockchain-gateway-v1/package.json
  packages/blockchain-ui/package-lock.json
  packages/blockchain-ui/package.json
  packages/blockchain-wallet/package-lock.json
  packages/blockchain-wallet/package.json
  packages/blockchain-website/package-lock.json
  packages/blockchain-website/package.json
Labels: merge-2648 pr
