Repository IBM-Blockchain/blockchain-vscode-extension, pull requests merged in 2020-05, with the labels that each got.

#2248 Fix docs autobuild (#2244)
  azure-templates/deploy-job.yml
Labels: v2 pr

#2254 Fix problems with environments
  packages/blockchain-common/src/registries/FabricEnvironmentRegistry.ts
  packages/blockchain-common/test/registries/FabricEnvironmentRegistry.test.ts
  packages/blockchain-extension/extension/explorer/environmentExplorer.ts
  packages/blockchain-extension/test/explorer/environmentExplorer.test.ts
Labels: v2 pr

#2251 Select package to deploy (close #1917)
  packages/blockchain-extension/extension/commands/openDeployView.ts
  packages/blockchain-ui/cypress.json
  packages/blockchain-ui/cypress/integration/deploy_page.spec.ts
  packages/blockchain-ui/enzyme/tests/App.test.tsx
  packages/blockchain-ui/enzyme/tests/ButtonList.test.tsx
  packages/blockchain-ui/enzyme/tests/DeployPage.test.tsx
  packages/blockchain-ui/enzyme/tests/DeployProgressBar.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepOne.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepThree.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepTwo.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepOne.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepThree.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepTwo.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/ButtonList.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/DeployPage.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/DeployProgressBar.test.tsx.snap
  packages/blockchain-ui/package.json
  packages/blockchain-ui/src/App.tsx
  packages/blockchain-ui/src/components/elements/ButtonList/ButtonList.scss
  packages/blockchain-ui/src/components/elements/ButtonList/ButtonList.tsx
  packages/blockchain-ui/src/components/elements/DeployProgressBar/DeployProgressBar.scss
  packages/blockchain-ui/src/components/elements/DeployProgressBar/DeployProgressBar.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepOne/DeployStepOne.scss
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepOne/DeployStepOne.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepThree/DeployStepThree.scss
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepThree/DeployStepThree.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepTwo/DeployStepTwo.scss
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepTwo/DeployStepTwo.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.scss
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.tsx
  packages/blockchain-ui/src/index.scss
  packages/blockchain-ui/src/interfaces/IPackageRegistryEntry.ts
Labels: v2 pr

#2256 Add policy to fabric-admin
  packages/blockchain-fabric-admin/.gitignore
  packages/blockchain-fabric-admin/cucumber/features/commit.feature
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/approve.steps.ts
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/commit.steps.ts
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/transaction.steps.ts
  packages/blockchain-fabric-admin/cucumber/helpers/ApproveHelper.ts
  packages/blockchain-fabric-admin/cucumber/helpers/CommitHelper.ts
  packages/blockchain-fabric-admin/cucumber/helpers/TransactionHelper.ts
  packages/blockchain-fabric-admin/package-lock.json
  packages/blockchain-fabric-admin/package.json
  packages/blockchain-fabric-admin/src/Lifecycle.ts
  packages/blockchain-fabric-admin/src/LifecycleChannel.ts
  packages/blockchain-fabric-admin/src/LifecycleCommon.ts
  packages/blockchain-fabric-admin/src/LifecyclePeer.ts
  packages/blockchain-fabric-admin/src/Policy.ts
  packages/blockchain-fabric-admin/src/pegjs/config.json
  packages/blockchain-fabric-admin/src/pegjs/endorsementPolicy.pegjs
  packages/blockchain-fabric-admin/src/pegjs/policyParser.ts
  packages/blockchain-fabric-admin/test/LifecycleChannel.test.ts
  packages/blockchain-fabric-admin/test/Policy.test.ts
Labels: v2 pr

#2257 Deploy contract (e2e) (close #1928)
  packages/blockchain-common/src/fabricModel/FabricCommittedSmartContract.ts
  packages/blockchain-common/src/interfaces/IFabricEnvironmentConnection.ts
  packages/blockchain-common/src/interfaces/IFabricGatewayConnection.ts
  packages/blockchain-common/test/fabricModel/fabricModel.test.ts
  packages/blockchain-environment-v1/src/FabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/test/FabricEnvironmentConnection.test.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/debug/FabricDebugConfigurationProvider.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/webview/DeployView.ts
  packages/blockchain-extension/test/debug/FabricDebugConfigurationProvider.test.ts
  packages/blockchain-extension/test/debug/FabricGoDebugConfigurationProvider.test.ts
  packages/blockchain-extension/test/debug/FabricJavaDebugConfigurationProvider.test.ts
  packages/blockchain-extension/test/debug/FabricNodeDebugConfigurationProvider.test.ts
  packages/blockchain-extension/test/webview/DeployView.test.ts
  packages/blockchain-gateway-v1/src/FabricConnection.ts
  packages/blockchain-gateway-v1/test/FabricConnection.test.ts
  packages/blockchain-ui/enzyme/tests/ButtonList.test.tsx
  packages/blockchain-ui/enzyme/tests/DeployPage.test.tsx
  packages/blockchain-ui/src/components/elements/ButtonList/ButtonList.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepOne/DeployStepOne.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepTwo/DeployStepTwo.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.tsx
Labels: v2 pr

#2267 Code server version, Java extension Pack fix, Ansible support
  docker/Dockerfile
  docker/README.md
  docker/media/diagram1.png
  docker/media/diagram2.png
Labels: v2 pr

#2291 Changelog (#2270)
  CHANGELOG.md
  packages/blockchain-extension/RELEASE-NOTES.md
  packages/blockchain-extension/tutorials/ibm-blockchain-platform-vscode-smart-contract/cloud-deploy.md
  packages/blockchain-extension/tutorials/ibm-blockchain-platform-vscode-smart-contract/cloud-setup.md
  packages/blockchain-extension/tutorials/new-tutorials/basic-tutorials/a1.md
  packages/blockchain-extension/tutorials/new-tutorials/basic-tutorials/a2.md
Labels: v2 pr

#2293 Amended changelog (#2277)
  CHANGELOG.md
  packages/blockchain-extension/RELEASE-NOTES.md
Labels: v2 pr

#2290 V2 Connect to IBM cloud - fix wording and multi-node orderer.
  README.md
  packages/blockchain-common/src/environments/FabricEnvironment.ts
  packages/blockchain-common/test/environments/FabricEnvironment.test.ts
  packages/blockchain-extension/cucumber/helpers/environmentHelper.ts
  packages/blockchain-extension/extension/commands/addEnvironmentCommand.ts
  packages/blockchain-extension/extension/commands/importNodesToEnvironmentCommand.ts
  packages/blockchain-extension/extension/configurations.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/addEnvironmentCommand.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
Labels: v2, v2 pr

#2295 Add support for feature flags (resolves #2268) (#2271)
  packages/blockchain-extension/ExtensionCommands.ts
  packages/blockchain-extension/extension/commands/manageFeatureFlags.ts
  packages/blockchain-extension/extension/configurations.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/util/FeatureFlags.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/manageFeatureFlags.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-extension/test/util/FeatureFlags.test.ts
Labels: v2 pr

#2296 Close view on deploy (close #1933)
  packages/blockchain-extension/extension/webview/DeployView.ts
  packages/blockchain-extension/test/webview/DeployView.test.ts
Labels: v2 pr

#2282 Update local fabric to v2
  packages/blockchain-extension/cucumber/features/deploy.feature
  packages/blockchain-extension/cucumber/features/evaluate.feature
  packages/blockchain-extension/cucumber/features/fabcar-sample.feature
  packages/blockchain-extension/cucumber/features/fabric-environments.feature
  packages/blockchain-extension/cucumber/features/fabric-gateways.feature
  packages/blockchain-extension/cucumber/features/install.feature
  packages/blockchain-extension/cucumber/features/instantiate.feature
  packages/blockchain-extension/cucumber/features/submit.feature
  packages/blockchain-extension/cucumber/features/upgrade.feature
  packages/blockchain-extension/cucumber/helpers/smartContractHelper.ts
  packages/blockchain-extension/cucumber/index.ts
  packages/blockchain-extension/cucumber/steps/deploy.steps.ts
  packages/blockchain-extension/cucumber/steps/index.ts
  packages/blockchain-extension/cucumber/steps/installInstantiateUpgrade.steps.ts
  packages/blockchain-extension/cucumber/steps/steps.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
Labels: v2 pr

#2289 View steps that will be perforned (Step 3) (close #1925)
  packages/blockchain-ui/enzyme/tests/ButtonList.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepThree.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepOne.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepThree.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/DeployPage.test.tsx.snap
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepOne/DeployStepOne.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepThree/DeployStepThree.scss
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepThree/DeployStepThree.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.scss
  packages/blockchain-ui/src/index.scss
  packages/blockchain-ui/src/mixins/theme-mixins.scss
Labels: v2 pr

#2300 Definition input validation (close #1922)
  packages/blockchain-ui/cypress/integration/deploy_page.spec.ts
  packages/blockchain-ui/enzyme/tests/DeployPage.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepTwo.test.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepTwo/DeployStepTwo.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.tsx
Labels: v2 pr

#2307 Fix v2 packaging
  lerna.json
  packages/blockchain-common/package-lock.json
  packages/blockchain-common/package.json
  packages/blockchain-environment-v1/package-lock.json
  packages/blockchain-environment-v1/package.json
  packages/blockchain-extension/extension/commands/deleteEnvironmentCommand.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-fabric-admin/package-lock.json
  packages/blockchain-fabric-admin/package.json
  packages/blockchain-gateway-v1/package-lock.json
  packages/blockchain-gateway-v1/package.json
  packages/blockchain-ui/package-lock.json
  packages/blockchain-ui/package.json
  packages/blockchain-wallet/package-lock.json
  packages/blockchain-wallet/package.json
  packages/blockchain-website/package-lock.json
  packages/blockchain-website/package.json
Labels: v2 pr

#2311 Allow creation of a Fablet environment (resolves #2280)
  packages/blockchain-common/index.ts
  packages/blockchain-common/src/environments/FabletEnvironment.ts
  packages/blockchain-common/src/registries/FabricEnvironmentRegistryEntry.ts
  packages/blockchain-common/src/registries/FabricGatewayRegistry.ts
  packages/blockchain-common/src/registries/FabricWalletRegistry.ts
  packages/blockchain-common/test/environments/FabletEnvironment.test.ts
  packages/blockchain-common/test/registries/FabricGatewayRegistry.test.ts
  packages/blockchain-common/test/registries/FabricWalletRegistry.test.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/commands/addEnvironmentCommand.ts
  packages/blockchain-extension/extension/fabric/environments/EnvironmentFactory.ts
  packages/blockchain-extension/test/TestUtil.ts
  packages/blockchain-extension/test/commands/addEnvironmentCommand.test.ts
  packages/blockchain-extension/test/fabric/environments/EnvironmentFactory.test.ts
Labels: v2 pr

#2262 Add policy to the extension
  packages/blockchain-common/index.ts
  packages/blockchain-common/src/fabricModel/FabricSmartContractDefinition.ts
  packages/blockchain-common/src/interfaces/IFabricEnvironmentConnection.ts
  packages/blockchain-common/src/interfaces/IFabricGatewayConnection.ts
  packages/blockchain-common/test/fabricModel/fabricModel.test.ts
  packages/blockchain-environment-v1/src/FabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/test/FabricEnvironmentConnection.test.ts
  packages/blockchain-extension/cucumber/helpers/smartContractHelper.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/commands/approveCommand.ts
  packages/blockchain-extension/extension/commands/commitCommand.ts
  packages/blockchain-extension/extension/commands/deployCommand.ts
  packages/blockchain-extension/extension/commands/installCommand.ts
  packages/blockchain-extension/extension/commands/openTransactionViewCommand.ts
  packages/blockchain-extension/extension/debug/FabricDebugConfigurationProvider.ts
  packages/blockchain-extension/extension/explorer/environmentExplorer.ts
  packages/blockchain-extension/extension/explorer/gatewayExplorer.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/webview/DeployView.ts
  packages/blockchain-extension/test/commands/UserInputUtil.test.ts
  packages/blockchain-extension/test/commands/approveCommand.test.ts
  packages/blockchain-extension/test/commands/commitCommand.test.ts
  packages/blockchain-extension/test/commands/debugCommandListCommand.test.ts
  packages/blockchain-extension/test/commands/deployCommand.test.ts
  packages/blockchain-extension/test/commands/installCommand.test.ts
  packages/blockchain-extension/test/commands/instantiateCommand.test.ts
  packages/blockchain-extension/test/commands/upgradeCommand.test.ts
  packages/blockchain-extension/test/debug/FabricDebugConfigurationProvider.test.ts
  packages/blockchain-extension/test/debug/FabricGoDebugConfigurationProvider.test.ts
  packages/blockchain-extension/test/debug/FabricJavaDebugConfigurationProvider.test.ts
  packages/blockchain-extension/test/debug/FabricNodeDebugConfigurationProvider.test.ts
  packages/blockchain-extension/test/explorer/environmentExplorer.test.ts
  packages/blockchain-extension/test/webview/DeployView.test.ts
  packages/blockchain-fabric-admin/package.json
  packages/blockchain-fabric-admin/src/Lifecycle.ts
  packages/blockchain-fabric-admin/src/LifecycleChannel.ts
  packages/blockchain-fabric-admin/test/Lifecycle.test.ts
  packages/blockchain-fabric-admin/test/LifecycleChannel.test.ts
  packages/blockchain-gateway-v1/src/FabricConnection.ts
Labels: v2 pr

#2306 Should be able to toggle commit (close #2228)
  packages/blockchain-extension/extension/commands/deployCommand.ts
  packages/blockchain-extension/test/commands/deployCommand.test.ts
  packages/blockchain-ui/cypress/integration/deploy_page.spec.ts
  packages/blockchain-ui/enzyme/tests/DeployPage.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepThree.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepThree.test.tsx.snap
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepThree/DeployStepThree.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.tsx
Labels: v2 pr

#2348 Eclipse Che and Fablet changes #2312, #2281, #2310 for v2 branch
  packages/blockchain-common/package-lock.json
  packages/blockchain-common/package.json
  packages/blockchain-common/src/environments/FabletClient.ts
  packages/blockchain-common/src/environments/FabletEnvironment.ts
  packages/blockchain-common/src/fabricModel/FabricNode.ts
  packages/blockchain-common/test/environments/FabletClient.test.ts
  packages/blockchain-common/test/environments/FabletEnvironment.test.ts
  packages/blockchain-environment-v1/src/FabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/test/FabricEnvironmentConnection.test.ts
  packages/blockchain-extension/extension/commands/addEnvironmentCommand.ts
  packages/blockchain-extension/extension/commands/importNodesToEnvironmentCommand.ts
  packages/blockchain-extension/extension/util/FileSystemSecureStore.ts
  packages/blockchain-extension/extension/util/KeytarSecureStore.ts
  packages/blockchain-extension/extension/util/SecureStore.ts
  packages/blockchain-extension/extension/util/SecureStoreFactory.ts
  packages/blockchain-extension/test/commands/addEnvironmentCommand.test.ts
  packages/blockchain-extension/test/commands/importNodesToEnvironmentCommand.test.ts
  packages/blockchain-extension/test/util/FileSystemSecureStore.test.ts
  packages/blockchain-extension/test/util/KeytarSecureStore.test.ts
  packages/blockchain-extension/test/util/SecureStoreFactory.test.ts
  packages/blockchain-fabric-admin/src/Lifecycle.ts
  packages/blockchain-fabric-admin/src/LifecyclePeer.ts
  packages/blockchain-fabric-admin/test/Lifecycle.test.ts
  packages/blockchain-fabric-admin/test/LifecyclePeer.test.ts
  packages/blockchain-fabric-admin/test/SmartContractPackage.test.ts
Labels: che, fablet, v2 pr

#2330 Add collections to fabric admin
  packages/blockchain-fabric-admin/cucumber/features/approve.feature
  packages/blockchain-fabric-admin/cucumber/features/commit.feature
  packages/blockchain-fabric-admin/cucumber/features/install.feature
  packages/blockchain-fabric-admin/cucumber/features/package.feature
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/approve.steps.ts
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/commit.steps.ts
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/package.steps.ts
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/transaction.steps.ts
  packages/blockchain-fabric-admin/cucumber/helpers/ApproveHelper.ts
  packages/blockchain-fabric-admin/cucumber/helpers/CommitHelper.ts
  packages/blockchain-fabric-admin/cucumber/helpers/Helper.ts
  packages/blockchain-fabric-admin/cucumber/helpers/TransactionHelper.ts
  packages/blockchain-fabric-admin/package.json
  packages/blockchain-fabric-admin/src/CollectionConfig.ts
  packages/blockchain-fabric-admin/src/LifecycleChannel.ts
  packages/blockchain-fabric-admin/src/index.ts
  packages/blockchain-fabric-admin/test/CollectionConfig.test.ts
  packages/blockchain-fabric-admin/test/LifecycleChannel.test.ts
Labels: v2 pr

#2333 Automatically create Fablet environment when available (resolves #2328)
  packages/blockchain-common/test/environments/FabletClient.test.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
Labels: fablet

#2368 Eclipse Che changes #2336, #2344 for v1 branch
  packages/blockchain-common/src/util/FileSystemUtil.ts
  packages/blockchain-common/test/util/FileSystemUtil.test.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/dependencies/DependencyManager.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/util/FileSystemSecureStore.ts
  packages/blockchain-extension/extension/util/SecureStoreFactory.ts
  packages/blockchain-extension/test/commands/UserInputUtil.test.ts
  packages/blockchain-extension/test/dependencies/DependencyManager.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-extension/test/util/SecureStoreFactory.test.ts
Labels: che

#2320 Fixed sizing in Step Two
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepTwo.test.tsx.snap
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepTwo/DeployStepTwo.tsx
Labels: v2 pr

#2371 Determine node label before node creation (resolves #2337)
  packages/blockchain-extension/extension/explorer/environmentExplorer.ts
  packages/blockchain-extension/extension/explorer/runtimeOps/connectedTree/NodeTreeItem.ts
  packages/blockchain-extension/test/explorer/environmentExplorer.test.ts
  packages/blockchain-extension/test/explorer/runtimeOps/NodeTreeItem.test.ts
Labels: che

#2366 Changelog & azure fix
  CHANGELOG.md
  azure-pipelines.yml
  packages/blockchain-extension/RELEASE-NOTES.md
Labels: v2 pr

#2373 Eclipse Che changes #2328, #2344, #2336, #2337 for v2 branch
  packages/blockchain-common/src/util/FileSystemUtil.ts
  packages/blockchain-common/test/environments/FabletClient.test.ts
  packages/blockchain-common/test/util/FileSystemUtil.test.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/dependencies/DependencyManager.ts
  packages/blockchain-extension/extension/explorer/environmentExplorer.ts
  packages/blockchain-extension/extension/explorer/runtimeOps/connectedTree/NodeTreeItem.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/util/FileSystemSecureStore.ts
  packages/blockchain-extension/extension/util/SecureStoreFactory.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/UserInputUtil.test.ts
  packages/blockchain-extension/test/dependencies/DependencyManager.test.ts
  packages/blockchain-extension/test/explorer/environmentExplorer.test.ts
  packages/blockchain-extension/test/explorer/runtimeOps/NodeTreeItem.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-extension/test/util/SecureStoreFactory.test.ts
Labels: che, v2 pr

#2375 Include IBM Cloud Account extension in Che package (resolves #2374)
  che/build.sh
Labels: che

#2322 Refresh deploy view on package change (close #2255)
  packages/blockchain-extension/extension/commands/deleteSmartContractPackageCommand.ts
  packages/blockchain-extension/extension/commands/importSmartContractPackageCommand.ts
  packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts
  packages/blockchain-extension/extension/explorer/runtimeOps/connectedTree/DeployTreeItem.ts
  packages/blockchain-extension/extension/webview/DeployView.ts
  packages/blockchain-extension/test/commands/deleteSmartContractPackageCommand.test.ts
  packages/blockchain-extension/test/commands/importSmartContractPackageCommand.test.ts
  packages/blockchain-extension/test/commands/packageSmartContractCommand.test.ts
  packages/blockchain-extension/test/explorer/environmentExplorer.test.ts
  packages/blockchain-extension/test/webview/DeployView.test.ts
  packages/blockchain-ui/enzyme/tests/DeployPage.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepOne.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepThree.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepThree.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/DeployPage.test.tsx.snap
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepOne/DeployStepOne.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepThree/DeployStepThree.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepTwo/DeployStepTwo.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.tsx
  packages/blockchain-ui/src/index.scss
  packages/blockchain-ui/src/interfaces/IPackageRegistryEntry.ts
Labels: v2 pr

#2379 Rename Fablet to Microfab (resolves #2378)
  packages/blockchain-common/index.ts
  packages/blockchain-common/src/environments/MicrofabClient.ts
  packages/blockchain-common/src/environments/MicrofabEnvironment.ts
  packages/blockchain-common/src/registries/FabricEnvironmentRegistryEntry.ts
  packages/blockchain-common/src/registries/FabricGatewayRegistry.ts
  packages/blockchain-common/src/registries/FabricWalletRegistry.ts
  packages/blockchain-common/test/environments/MicrofabClient.test.ts
  packages/blockchain-common/test/environments/MicrofabEnvironment.test.ts
  packages/blockchain-common/test/registries/FabricGatewayRegistry.test.ts
  packages/blockchain-common/test/registries/FabricWalletRegistry.test.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/commands/addEnvironmentCommand.ts
  packages/blockchain-extension/extension/fabric/environments/EnvironmentFactory.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/util/FeatureFlags.ts
  packages/blockchain-extension/test/commands/addEnvironmentCommand.test.ts
  packages/blockchain-extension/test/commands/manageFeatureFlags.test.ts
  packages/blockchain-extension/test/fabric/environments/EnvironmentFactory.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-extension/test/util/FeatureFlags.test.ts
Labels: microfab

#2380 Update changelog
  CHANGELOG.md
  azure-templates/deploy-job.yml
  lerna.json
  packages/blockchain-common/package-lock.json
  packages/blockchain-common/package.json
  packages/blockchain-environment-v1/package-lock.json
  packages/blockchain-environment-v1/package.json
  packages/blockchain-extension/RELEASE-NOTES.md
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-fabric-admin/package-lock.json
  packages/blockchain-fabric-admin/package.json
  packages/blockchain-gateway-v1/package-lock.json
  packages/blockchain-gateway-v1/package.json
  packages/blockchain-ui/package-lock.json
  packages/blockchain-ui/package.json
  packages/blockchain-wallet/package-lock.json
  packages/blockchain-wallet/package.json
  packages/blockchain-website/package-lock.json
  packages/blockchain-website/package.json
Labels: v2 pr

#2383 Show home page at first activation in a Che workspace (resolves #2338)
  che/build.sh
Labels: che

#2382 Rename Fablet to Microfab (resolves #2378)
  packages/blockchain-common/index.ts
  packages/blockchain-common/src/environments/MicrofabClient.ts
  packages/blockchain-common/src/environments/MicrofabEnvironment.ts
  packages/blockchain-common/src/registries/FabricEnvironmentRegistryEntry.ts
  packages/blockchain-common/src/registries/FabricGatewayRegistry.ts
  packages/blockchain-common/src/registries/FabricWalletRegistry.ts
  packages/blockchain-common/test/environments/MicrofabClient.test.ts
  packages/blockchain-common/test/environments/MicrofabEnvironment.test.ts
  packages/blockchain-common/test/registries/FabricGatewayRegistry.test.ts
  packages/blockchain-common/test/registries/FabricWalletRegistry.test.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/commands/addEnvironmentCommand.ts
  packages/blockchain-extension/extension/fabric/environments/EnvironmentFactory.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/util/FeatureFlags.ts
  packages/blockchain-extension/test/commands/addEnvironmentCommand.test.ts
  packages/blockchain-extension/test/commands/manageFeatureFlags.test.ts
  packages/blockchain-extension/test/fabric/environments/EnvironmentFactory.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-extension/test/util/FeatureFlags.test.ts
Labels: microfab, v2 pr

#2387 Upgrade to generator-fabric@0.1.12 (resolves #2386)
  packages/blockchain-extension/cucumber/features/package.feature
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
Labels: che, microfab

#2389 Get discovered peer names
  packages/blockchain-fabric-admin/cucumber/features/discover.feature
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/discover.steps.ts
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/network.steps.ts
  packages/blockchain-fabric-admin/cucumber/helpers/DiscoverHelper.ts
  packages/blockchain-fabric-admin/cucumber/helpers/NetworkHelper.ts
  packages/blockchain-fabric-admin/package.json
  packages/blockchain-fabric-admin/src/LifecycleChannel.ts
  packages/blockchain-fabric-admin/test/LifecycleChannel.test.ts
Labels: v2 pr

#2396 Fix deploy problem
  packages/blockchain-environment-v1/src/FabricEnvironmentConnection.ts
  packages/blockchain-extension/extension/webview/DeployView.ts
  packages/blockchain-extension/test/webview/DeployView.test.ts
Labels: v2 pr

#2385 Package open project (close #1918)
  packages/blockchain-extension/extension/commands/openDeployView.ts
  packages/blockchain-extension/extension/webview/DeployView.ts
  packages/blockchain-extension/test/commands/openDeployView.test.ts
  packages/blockchain-extension/test/webview/DeployView.test.ts
  packages/blockchain-ui/cypress/integration/deploy_page.spec.ts
  packages/blockchain-ui/enzyme/tests/App.test.tsx
  packages/blockchain-ui/enzyme/tests/DeployPage.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepOne.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/DeployStepThree.test.tsx
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepOne.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/DeploySteps/__snapshots__/DeployStepThree.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/DeployPage.test.tsx.snap
  packages/blockchain-ui/src/App.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepOne/DeployStepOne.tsx
  packages/blockchain-ui/src/components/elements/DeploySteps/DeployStepThree/DeployStepThree.tsx
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.scss
  packages/blockchain-ui/src/components/pages/DeployPage/DeployPage.tsx
  packages/blockchain-ui/src/mixins/theme-mixins.scss
Labels: v2 pr

#2398 Explicitly disable local Fabric on Eclipse Che (resolves #2394)
  packages/blockchain-extension/extension/commands/restartFabricRuntime.ts
  packages/blockchain-extension/extension/commands/startFabricRuntime.ts
  packages/blockchain-extension/extension/commands/stopFabricRuntime.ts
  packages/blockchain-extension/extension/commands/teardownFabricRuntime.ts
  packages/blockchain-extension/extension/debug/FabricDebugConfigurationProvider.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/restartFabricRuntime.test.ts
  packages/blockchain-extension/test/commands/startFabricRuntime.test.ts
  packages/blockchain-extension/test/commands/stopFabricRuntime.test.ts
  packages/blockchain-extension/test/commands/teardownFabricRuntime.test.ts
  packages/blockchain-extension/test/debug/FabricDebugConfigurationProvider.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
Labels: che

#2400 Explicitly disable local Fabric on Eclipse Che (resolves #2394)
  packages/blockchain-extension/extension/commands/restartFabricRuntime.ts
  packages/blockchain-extension/extension/commands/startFabricRuntime.ts
  packages/blockchain-extension/extension/commands/stopFabricRuntime.ts
  packages/blockchain-extension/extension/commands/teardownFabricRuntime.ts
  packages/blockchain-extension/extension/debug/FabricDebugConfigurationProvider.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/restartFabricRuntime.test.ts
  packages/blockchain-extension/test/commands/startFabricRuntime.test.ts
  packages/blockchain-extension/test/commands/stopFabricRuntime.test.ts
  packages/blockchain-extension/test/commands/teardownFabricRuntime.test.ts
  packages/blockchain-extension/test/debug/FabricDebugConfigurationProvider.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
Labels: che, v2 pr

#2403 Publish a Che metadata file without the version (resolves #2402)
  che/build.sh
Labels: che
