Repository IBM-Blockchain/blockchain-vscode-extension, pull requests merged in 2020-11, with the labels that each got.

#2782 Updated a3 tutorial
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a3.md
Labels: merge-2648 pr

#2783 Fix packaging metadata path
  packages/blockchain-environment-v1/test/PackageSmartContract.test.ts
  packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts
  packages/blockchain-extension/test/commands/packageSmartContractCommand.test.ts
Labels: merge-2648 pr

#2784 Changelog (v2)
  CHANGELOG.md
  packages/blockchain-extension/RELEASE-NOTES.md
Labels: merge-2648 pr

#2789 Enable IBP 2.5.1 support
  packages/blockchain-common/src/fabricModel/FabricNode.ts
  packages/blockchain-extension/extension/commands/addEnvironmentCommand.ts
  packages/blockchain-extension/extension/commands/environmentConnectCommand.ts
  packages/blockchain-extension/extension/commands/importNodesToEnvironmentCommand.ts
  packages/blockchain-extension/extension/commands/logInAndDiscoverCommand.ts
  packages/blockchain-extension/extension/configurations.ts
  packages/blockchain-extension/extension/explorer/environmentExplorer.ts
  packages/blockchain-extension/extension/util/ExtensionsInteractionUtil.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/deleteEnvironmentCommand.test.ts
  packages/blockchain-extension/test/commands/environmentConnectCommand.test.ts
  packages/blockchain-extension/test/commands/importNodesToEnvironmentCommand.test.ts
  packages/blockchain-extension/test/explorer/environmentExplorer.test.ts
Labels: v2 pr

#2791 Updates for IBP 2.5.1
  packages/blockchain-common/src/fabricModel/FabricNode.ts
  packages/blockchain-extension/extension/commands/addEnvironmentCommand.ts
  packages/blockchain-extension/extension/commands/importNodesToEnvironmentCommand.ts
  packages/blockchain-extension/test/commands/importNodesToEnvironmentCommand.test.ts
Labels: ignore-v2

#2793 Update environment panel images
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a2.2-a3.2.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a3.3.2.png
Labels: v2 pr

#2797 Revert "Fix packaging metadata path (#2755)"
  packages/blockchain-environment-v1/test/PackageSmartContract.test.ts
  packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts
  packages/blockchain-extension/test/commands/packageSmartContractCommand.test.ts
Labels: ignore-v2

#2798 Revert "Fix packaging metadata path (#2772)"
  packages/blockchain-environment-v1/test/PackageSmartContract.test.ts
  packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts
  packages/blockchain-extension/test/commands/packageSmartContractCommand.test.ts
Labels: ignore-merge-2648, v2 pr

#2778 Transaction View React Components
  packages/blockchain-extension/extension/commands/associateTransactionDataDirectoryCommand.ts
  packages/blockchain-extension/extension/commands/dissociateTransactionDataDirectoryCommand.ts
  packages/blockchain-extension/extension/commands/openTransactionViewCommand.ts
  packages/blockchain-extension/extension/commands/submitTransaction.ts
  packages/blockchain-extension/extension/explorer/gatewayExplorer.ts
  packages/blockchain-extension/extension/explorer/model/TransactionTreeItem.ts
  packages/blockchain-extension/extension/interfaces/IAssociateFromViewOptions.ts
  packages/blockchain-extension/extension/interfaces/ITransaction.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/webview/TransactionView.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/associateTransactionDataDirectoryCommand.test.ts
  packages/blockchain-extension/test/commands/dissociateTransactionDataDirectoryCommand.test.ts
  packages/blockchain-extension/test/commands/importNodesToEnvironmentCommand.test.ts
  packages/blockchain-extension/test/commands/openTransactionViewCommand.test.ts
  packages/blockchain-extension/test/commands/submitTransaction.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-extension/test/webview/TransactionView.test.ts
  packages/blockchain-ui/cypress/integration/transaction_page.spec.ts
  packages/blockchain-ui/enzyme/tests/App.test.tsx
  packages/blockchain-ui/enzyme/tests/TransactionForm.test.tsx
  packages/blockchain-ui/enzyme/tests/TransactionInputContainer.test.tsx
  packages/blockchain-ui/enzyme/tests/TransactionPage.test.tsx
  packages/blockchain-ui/enzyme/tests/__snapshots__/TransactionInputContainer.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/TransactionOutput.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/TransactionPage.test.tsx.snap
  packages/blockchain-ui/src/App.scss
  packages/blockchain-ui/src/App.tsx
  packages/blockchain-ui/src/components/elements/CommandLink/CommandLink.tsx
  packages/blockchain-ui/src/components/elements/TransactionDataInput/TransactionDataInput.scss
  packages/blockchain-ui/src/components/elements/TransactionDataInput/TransactionDataInput.tsx
  packages/blockchain-ui/src/components/elements/TransactionForm/TransactionForm.tsx
  packages/blockchain-ui/src/components/elements/TransactionInputContainer/TransactionInputContainer.tsx
  packages/blockchain-ui/src/components/elements/TransactionManualInput/TransactionManualInput.scss
  packages/blockchain-ui/src/components/elements/TransactionManualInput/TransactionManualInput.tsx
  packages/blockchain-ui/src/components/elements/TransactionOutput/TransactionOutput.scss
  packages/blockchain-ui/src/components/elements/TransactionOutput/TransactionOutput.tsx
  packages/blockchain-ui/src/components/elements/TransactionSubmitButtons/TransactionSubmitButtons.scss
  packages/blockchain-ui/src/components/elements/TransactionSubmitButtons/TransactionSubmitButtons.tsx
  packages/blockchain-ui/src/components/elements/TutorialMarkdown/TutorialMarkdown.tsx
  packages/blockchain-ui/src/components/elements/TutorialTile/TutorialTile.tsx
  packages/blockchain-ui/src/components/pages/TransactionPage/TransactionPage.scss
  packages/blockchain-ui/src/components/pages/TransactionPage/TransactionPage.tsx
  packages/blockchain-ui/src/index.scss
  packages/blockchain-ui/src/interfaces/IAssociatedTxdata.ts
  packages/blockchain-ui/src/interfaces/IDataFileTransaction.ts
  packages/blockchain-ui/src/interfaces/ITransactionManualInput.ts
  packages/blockchain-ui/src/resources/block.svg
Labels: v2 pr

#2808 Remove instantiate and upgrade commands from palette
  packages/blockchain-extension/package.json
Labels: v2 pr

#2809 Updated transaction tutorials
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a4.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a6.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a9.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a4.10.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a4.11.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a4.12.0.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a4.13.1.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a4.13.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a4.14.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a4.15.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a4.6.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a4.7.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a4.8-a9.19.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a4.8.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a6.19.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a9.17-a9.28.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a9.17.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a9.18.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a9.28.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a9.29.1.png
Labels: v2 pr

#2801 Changelog
  CHANGELOG.md
  packages/blockchain-extension/RELEASE-NOTES.md
Labels: ignore-v2

#2814 Transaction View - Guard against empty transaction parameters, fix css for light mode
  packages/blockchain-ui/enzyme/tests/TransactionInputContainer.test.tsx
  packages/blockchain-ui/enzyme/tests/__snapshots__/TransactionInputContainer.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/TransactionPage.test.tsx.snap
  packages/blockchain-ui/src/components/elements/TransactionInputContainer/TransactionInputContainer.scss
  packages/blockchain-ui/src/components/elements/TransactionInputContainer/TransactionInputContainer.tsx
  packages/blockchain-ui/src/components/elements/TransactionManualInput/TransactionManualInput.tsx
  packages/blockchain-ui/src/components/elements/TransactionOutput/TransactionOutput.scss
  packages/blockchain-ui/src/components/pages/TransactionPage/TransactionPage.scss
  packages/blockchain-ui/src/index.scss
Labels: v2 pr

#2799 Revert "Fix packaging metadata path"
  packages/blockchain-environment-v1/test/PackageSmartContract.test.ts
  packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts
  packages/blockchain-extension/test/commands/packageSmartContractCommand.test.ts
Labels: merge-2648 pr

#2804 Changelog (v2)
  CHANGELOG.md
  packages/blockchain-extension/RELEASE-NOTES.md
Labels: v2 pr

#2788 [merge] instantiate and upgrade
  packages/blockchain-common/src/interfaces/IFabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/package-lock.json
  packages/blockchain-environment-v1/package.json
  packages/blockchain-environment-v1/src/FabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/test/FabricEnvironmentConnection.test.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/commands/instantiateCommand.ts
  packages/blockchain-extension/extension/commands/upgradeCommand.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/resources/package.json
  packages/blockchain-extension/test/commands/UserInputUtil.test.ts
  packages/blockchain-extension/test/commands/instantiateCommand.test.ts
  packages/blockchain-extension/test/commands/upgradeCommand.test.ts
  packages/blockchain-fabric-admin/package-lock.json
  packages/blockchain-fabric-admin/package.json
  packages/blockchain-fabric-admin/src/LifecycleChannel.ts
  packages/blockchain-fabric-admin/test/LifecycleChannel.test.ts
  packages/blockchain-fabric-admin/test/data/node/package.json
  packages/blockchain-gateway-v1/package-lock.json
  packages/blockchain-gateway-v1/package.json
  packages/blockchain-wallet/package-lock.json
  packages/blockchain-wallet/package.json
Labels: merge-2648 pr

#2825 Choose network capabilities (close #2657)
  packages/blockchain-common/src/interfaces/IFabricGatewayConnection.ts
  packages/blockchain-common/src/registries/FabricEnvironmentRegistryEntry.ts
  packages/blockchain-common/test/registries/FabricGatewayRegistry.test.ts
  packages/blockchain-common/test/registries/FabricWalletRegistry.test.ts
  packages/blockchain-extension/cucumber/features/fabcar-sample.feature
  packages/blockchain-extension/cucumber/features/fabric-environments.feature
  packages/blockchain-extension/cucumber/helpers/environmentHelper.ts
  packages/blockchain-extension/cucumber/helpers/smartContractHelper.ts
  packages/blockchain-extension/cucumber/helpers/userInputUtilHelper.ts
  packages/blockchain-extension/cucumber/steps/fabricEnvironment.steps.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/commands/addEnvironmentCommand.ts
  packages/blockchain-extension/extension/commands/createSmartContractProjectCommand.ts
  packages/blockchain-extension/extension/explorer/environmentExplorer.ts
  packages/blockchain-extension/extension/explorer/gatewayExplorer.ts
  packages/blockchain-extension/extension/explorer/model/ChannelTreeItem.ts
  packages/blockchain-extension/extension/fabric/environments/LocalMicroEnvironment.ts
  packages/blockchain-extension/extension/fabric/environments/LocalMicroEnvironmentManager.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-extension/scripts/installdocker.sh
  packages/blockchain-extension/test/commands/UserInputUtil.test.ts
  packages/blockchain-extension/test/commands/addEnvironmentCommand.test.ts
  packages/blockchain-extension/test/commands/addWalletIdentityCommand.test.ts
  packages/blockchain-extension/test/commands/associateTransactionDataDirectoryCommand.test.ts
  packages/blockchain-extension/test/commands/createSmartContractProjectCommand.test.ts
  packages/blockchain-extension/test/commands/deleteEnvironmentCommand.test.ts
  packages/blockchain-extension/test/commands/dissociateTransactionDataDirectoryCommand.test.ts
  packages/blockchain-extension/test/commands/environmentConnectCommand.test.ts
  packages/blockchain-extension/test/commands/exportAppData.test.ts
  packages/blockchain-extension/test/commands/openTransactionViewCommand.test.ts
  packages/blockchain-extension/test/commands/submitTransaction.test.ts
  packages/blockchain-extension/test/commands/subscribeToEventCommand.test.ts
  packages/blockchain-extension/test/commands/testSmartContractCommand.test.ts
  packages/blockchain-extension/test/data/1 Org Local Fabric/.config.json
  packages/blockchain-extension/test/explorer/environmentExplorer.test.ts
  packages/blockchain-extension/test/explorer/gatewayExplorer.test.ts
  packages/blockchain-extension/test/explorer/model/InstantiatedTreeItem.test.ts
  packages/blockchain-extension/test/explorer/model/LocalGatewayTreeItem.test.ts
  packages/blockchain-extension/test/explorer/runtimeOps/RuntimeTreeItem.test.ts
  packages/blockchain-extension/test/fabric/environments/EnvironmentFactory.test.ts
  packages/blockchain-extension/test/fabric/environments/LocalMicroEnvironment.test.ts
  packages/blockchain-extension/test/fabric/environments/LocalMicroEnvironmentManager.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-gateway-v1/src/FabricConnection.ts
  packages/blockchain-gateway-v1/test/FabricConnection.test.ts
  packages/test/tmp/v2/environments/1 Org Local Fabric/.config.json
  test/data/1 Org Local Fabric/.config.json
Labels: merge-2648 pr

#2827 Remove chaincode timeout setting (close #2826)
  packages/blockchain-extension/extension/configurations.ts
  packages/blockchain-extension/extension/fabric/environments/LocalMicroEnvironment.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/debug/FabricDebugConfigurationProvider.test.ts
  packages/blockchain-extension/test/fabric/environments/LocalMicroEnvironment.test.ts
Labels: merge-2648 pr

#2820 [merge] Add Fabric V1 packaging capabilities
  packages/blockchain-environment-v1/src/ListFilesInPackage.ts
  packages/blockchain-environment-v1/src/PackageSmartContract.ts
  packages/blockchain-environment-v1/test/ListFilesInPackage.test.ts
  packages/blockchain-environment-v1/test/PackageSmartContract.test.ts
  packages/blockchain-environment-v1/test/data/packages/typescript-v1-contract.cds
  packages/blockchain-extension/cucumber/features/package.feature
  packages/blockchain-extension/cucumber/helpers/smartContractHelper.ts
  packages/blockchain-extension/cucumber/index.ts
  packages/blockchain-extension/cucumber/steps/package.steps.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts
  packages/blockchain-extension/extension/explorer/packageExplorer.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/test/commands/UserInputUtil.test.ts
  packages/blockchain-extension/test/commands/packageSmartContractCommand.test.ts
  packages/blockchain-extension/test/explorer/packageExplorer.test.ts
  packages/blockchain-fabric-admin/cucumber/features/approve.feature
  packages/blockchain-fabric-admin/cucumber/features/commit.feature
  packages/blockchain-fabric-admin/cucumber/features/discover.feature
  packages/blockchain-fabric-admin/cucumber/features/install.feature
  packages/blockchain-fabric-admin/cucumber/features/package.feature
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/approve.steps.ts
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/commit.steps.ts
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/package.steps.ts
  packages/blockchain-fabric-admin/cucumber/features/step_definitions/transaction.steps.ts
  packages/blockchain-fabric-admin/cucumber/helpers/PackageHelper.ts
  packages/blockchain-fabric-admin/src/SmartContractPackageBase.ts
  packages/blockchain-fabric-admin/src/V1SmartContractPackage.ts
  packages/blockchain-fabric-admin/src/V2SmartContractPackage.ts
  packages/blockchain-fabric-admin/src/index.ts
  packages/blockchain-fabric-admin/test/SmartContractPackage.test.ts
  packages/blockchain-fabric-admin/test/data/packages/typescript-v1-contract.cds
Labels: merge-2648 pr

#2830 [merge] create v2 identities in v1 wallets
  packages/blockchain-common/src/interfaces/IFabricWallet.ts
  packages/blockchain-common/test/environments/MicrofabEnvironment.test.ts
  packages/blockchain-extension/extension/commands/addWalletCommand.ts
  packages/blockchain-extension/test/commands/addWalletCommand.test.ts
  packages/blockchain-wallet/.vscode/launch.json
  packages/blockchain-wallet/package-lock.json
  packages/blockchain-wallet/package.json
  packages/blockchain-wallet/src/FabricWallet.ts
  packages/blockchain-wallet/test/FabricWallet.test.ts
Labels: merge-2648 pr
