Repository IBM-Blockchain/blockchain-vscode-extension, pull requests merged in 2020-10, with the labels that each got.

#2642 Reintroduce webview for submitting transactions on v2
  packages/blockchain-extension/extension/webview/TransactionView.ts
  packages/blockchain-extension/test/webview/TransactionView.test.ts
  packages/blockchain-ui/cypress/integration/transaction_page.spec.ts
  packages/blockchain-ui/enzyme/tests/App.test.tsx
  packages/blockchain-ui/enzyme/tests/TransactionForm.test.tsx
  packages/blockchain-ui/enzyme/tests/TransactionOutput.test.tsx
  packages/blockchain-ui/enzyme/tests/TransactionPage.test.tsx
  packages/blockchain-ui/enzyme/tests/__snapshots__/TransactionForm.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/TransactionOutput.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/TransactionPage.test.tsx.snap
  packages/blockchain-ui/src/App.tsx
  packages/blockchain-ui/src/components/elements/TransactionForm/TransactionForm.scss
  packages/blockchain-ui/src/components/elements/TransactionForm/TransactionForm.tsx
  packages/blockchain-ui/src/components/elements/TransactionOutput/TransactionOutput.scss
  packages/blockchain-ui/src/components/elements/TransactionOutput/TransactionOutput.tsx
  packages/blockchain-ui/src/components/pages/TransactionPage/TransactionPage.scss
  packages/blockchain-ui/src/components/pages/TransactionPage/TransactionPage.tsx
  packages/blockchain-ui/src/components/transactionView/TransactionOutput/TransactionOutput.scss
  packages/blockchain-ui/src/mixins/theme-mixins.scss
Labels: v2 pr

#2673 Make Node runner optional
  packages/blockchain-extension/extension/dependencies/Dependencies.ts
  packages/blockchain-extension/extension/dependencies/DependencyManager.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/dependencies/DependencyManager.test.ts
Labels: v2 pr

#2674 Removed js runner from package.json
  packages/blockchain-extension/package.json
Labels: ignore-v2

#2628 Updated C++ build tools check for Windows
  packages/blockchain-extension/extension/dependencies/DependencyManager.ts
  packages/blockchain-extension/test/dependencies/DependencyManager.test.ts
Labels: ignore-v2

#2585 [v2] - Connect to environment/gateway if at least one of the channels is v2 enabled.
  packages/blockchain-common/src/interfaces/IFabricEnvironmentConnection.ts
  packages/blockchain-common/src/interfaces/IFabricGatewayConnection.ts
  packages/blockchain-environment-v1/src/FabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/test/FabricEnvironmentConnection.test.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/commands/debugCommandListCommand.ts
  packages/blockchain-extension/extension/commands/environmentConnectCommand.ts
  packages/blockchain-extension/extension/commands/gatewayConnectCommand.ts
  packages/blockchain-extension/extension/commands/openDeployView.ts
  packages/blockchain-extension/extension/commands/openTransactionViewCommand.ts
  packages/blockchain-extension/extension/explorer/environmentExplorer.ts
  packages/blockchain-extension/extension/explorer/gatewayExplorer.ts
  packages/blockchain-extension/extension/webview/DeployView.ts
  packages/blockchain-extension/test/commands/UserInputUtil.test.ts
  packages/blockchain-extension/test/commands/associateTransactionDataDirectoryCommand.test.ts
  packages/blockchain-extension/test/commands/createNewIdentityCommand.test.ts
  packages/blockchain-extension/test/commands/debugCommandListCommand.test.ts
  packages/blockchain-extension/test/commands/dissociateTransactionDataDirectoryCommand.test.ts
  packages/blockchain-extension/test/commands/environmentConnectCommand.test.ts
  packages/blockchain-extension/test/commands/exportAppData.test.ts
  packages/blockchain-extension/test/commands/gatewayConnectCommand.test.ts
  packages/blockchain-extension/test/commands/instantiateCommand.test.ts
  packages/blockchain-extension/test/commands/openDeployView.test.ts
  packages/blockchain-extension/test/commands/openTransactionViewCommand.test.ts
  packages/blockchain-extension/test/commands/submitTransaction.test.ts
  packages/blockchain-extension/test/commands/subscribeToEventCommand.test.ts
  packages/blockchain-extension/test/commands/testSmartContractCommand.test.ts
  packages/blockchain-extension/test/commands/upgradeCommand.test.ts
  packages/blockchain-extension/test/explorer/environmentExplorer.test.ts
  packages/blockchain-extension/test/explorer/gatewayExplorer.test.ts
  packages/blockchain-extension/test/webview/DeployView.test.ts
  packages/blockchain-gateway-v1/src/FabricConnection.ts
  packages/blockchain-gateway-v1/test/FabricConnection.test.ts
Labels: v2 pr

#2624 v1 - display only v1 channels
  packages/blockchain-common/src/interfaces/IFabricEnvironmentConnection.ts
  packages/blockchain-common/src/interfaces/IFabricGatewayConnection.ts
  packages/blockchain-environment-v1/package-lock.json
  packages/blockchain-environment-v1/package.json
  packages/blockchain-environment-v1/src/FabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/test/FabricEnvironmentConnection.test.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/commands/debugCommandListCommand.ts
  packages/blockchain-extension/extension/commands/environmentConnectCommand.ts
  packages/blockchain-extension/extension/commands/gatewayConnectCommand.ts
  packages/blockchain-extension/extension/commands/openTransactionViewCommand.ts
  packages/blockchain-extension/extension/explorer/environmentExplorer.ts
  packages/blockchain-extension/extension/explorer/gatewayExplorer.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/test/commands/UserInputUtil.test.ts
  packages/blockchain-extension/test/commands/associateTransactionDataDirectoryCommand.test.ts
  packages/blockchain-extension/test/commands/debugCommandListCommand.test.ts
  packages/blockchain-extension/test/commands/dissociateTransactionDataDirectoryCommand.test.ts
  packages/blockchain-extension/test/commands/environmentConnectCommand.test.ts
  packages/blockchain-extension/test/commands/exportAppData.test.ts
  packages/blockchain-extension/test/commands/gatewayConnectCommand.test.ts
  packages/blockchain-extension/test/commands/instantiateCommand.test.ts
  packages/blockchain-extension/test/commands/openTransactionViewCommand.test.ts
  packages/blockchain-extension/test/commands/submitTransaction.test.ts
  packages/blockchain-extension/test/commands/subscribeToEventCommand.test.ts
  packages/blockchain-extension/test/commands/testSmartContractCommand.test.ts
  packages/blockchain-extension/test/commands/upgradeCommand.test.ts
  packages/blockchain-extension/test/explorer/environmentExplorer.test.ts
  packages/blockchain-extension/test/explorer/gatewayExplorer.test.ts
  packages/blockchain-extension/tutorials/new-tutorials/basic-tutorials/resources/package.json
  packages/blockchain-gateway-v1/package-lock.json
  packages/blockchain-gateway-v1/package.json
  packages/blockchain-gateway-v1/src/FabricConnection.ts
  packages/blockchain-gateway-v1/test/FabricConnection.test.ts
  packages/blockchain-wallet/package-lock.json
  packages/blockchain-wallet/package.json
Labels: ignore-v2

#2694 v2 - update node prereqs
  README.md
  packages/blockchain-extension/extension/dependencies/Dependencies.ts
  packages/blockchain-extension/extension/webview/PreReqView.ts
  packages/blockchain-extension/test/dependencies/DependencyManager.test.ts
  packages/blockchain-extension/test/webview/PreReqView.test.ts
Labels: v2 pr

#2711 [v2] - fix openSSL
  README.md
  packages/blockchain-extension/extension/dependencies/Dependencies.ts
  packages/blockchain-extension/extension/dependencies/DependencyManager.ts
  packages/blockchain-extension/test/dependencies/DependencyManager.test.ts
Labels: v2 pr

#2710 [v1] - fix openSSL label and tooltip in pre-reqs, and link to binaries page
  README.md
  packages/blockchain-extension/extension/dependencies/DependencyManager.ts
  packages/blockchain-extension/test/dependencies/DependencyManager.test.ts
Labels: ignore-v2

#2705 Add go mod vendor command if go.mod file exists
  packages/blockchain-extension/cucumber/features/package.feature
  packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts
  packages/blockchain-extension/test/commands/packageSmartContractCommand.test.ts
Labels: hacktoberfest-accepted, ignore-v2

#2709 Changelog (v2)
  CHANGELOG.md
  packages/blockchain-extension/RELEASE-NOTES.md
Labels: v2 pr

#2708 Changelog
  CHANGELOG.md
  packages/blockchain-extension/RELEASE-NOTES.md
Labels: ignore-v2

#2649 Add peer targeting to transaction view
  packages/blockchain-extension/extension/commands/openTransactionViewCommand.ts
  packages/blockchain-extension/extension/commands/submitTransaction.ts
  packages/blockchain-extension/test/commands/openTransactionViewCommand.test.ts
  packages/blockchain-extension/test/commands/submitTransaction.test.ts
  packages/blockchain-ui/cypress/integration/transaction_page.spec.ts
  packages/blockchain-ui/enzyme/tests/App.test.tsx
  packages/blockchain-ui/enzyme/tests/TransactionForm.test.tsx
  packages/blockchain-ui/enzyme/tests/TransactionPage.test.tsx
  packages/blockchain-ui/enzyme/tests/__snapshots__/TransactionForm.test.tsx.snap
  packages/blockchain-ui/enzyme/tests/__snapshots__/TransactionPage.test.tsx.snap
  packages/blockchain-ui/src/App.tsx
  packages/blockchain-ui/src/components/elements/TransactionForm/TransactionForm.tsx
  packages/blockchain-ui/src/interfaces/ISmartContract.ts
Labels: v2 pr

#2707 [v2 merge] - install cds from command palette
  packages/blockchain-common/src/interfaces/IFabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/src/FabricEnvironmentConnection.ts
  packages/blockchain-environment-v1/test/FabricEnvironmentConnection.test.ts
  packages/blockchain-extension/extension/commands/UserInputUtil.ts
  packages/blockchain-extension/extension/commands/installCommand.ts
  packages/blockchain-extension/extension/registries/PackageRegistry.ts
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/UserInputUtil.test.ts
  packages/blockchain-extension/test/commands/installCommand.test.ts
  packages/blockchain-fabric-admin/src/LifecyclePeer.ts
  packages/blockchain-fabric-admin/test/LifecycleChannel.test.ts
  packages/blockchain-fabric-admin/test/LifecyclePeer.test.ts
  packages/blockchain-gateway-v1/src/FabricConnection.ts
  packages/blockchain-gateway-v1/test/FabricConnection.test.ts
Labels: hacktoberfest-accepted, merge-2648 pr

#2696 [v2] Only let users generate v2 contracts
  packages/blockchain-extension/extension/commands/createSmartContractProjectCommand.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
Labels: v2 pr

#2697 [merge-2648] Let users choose between v1 and v2 contracts
  packages/blockchain-extension/cucumber/features/create.feature
  packages/blockchain-extension/cucumber/features/deploy.feature
  packages/blockchain-extension/cucumber/features/evaluate.feature
  packages/blockchain-extension/cucumber/features/fabric-environments.feature
  packages/blockchain-extension/cucumber/features/fabric-gateways.feature
  packages/blockchain-extension/cucumber/features/package.feature
  packages/blockchain-extension/cucumber/features/submit.feature
  packages/blockchain-extension/cucumber/features/upgrade.feature
  packages/blockchain-extension/cucumber/helpers/smartContractHelper.ts
  packages/blockchain-extension/cucumber/steps/smartContract.steps.ts
  packages/blockchain-extension/extension/commands/createSmartContractProjectCommand.ts
  packages/blockchain-extension/package-lock.json
  packages/blockchain-extension/package.json
  packages/blockchain-extension/test/commands/createSmartContractProjectCommand.test.ts
Labels: merge-2648 pr

#2723 Add initial IBM Account extension code to V2, further Dependency refactor
  packages/blockchain-extension/ExtensionCommands.ts
  packages/blockchain-extension/extension/dependencies/Dependencies.ts
  packages/blockchain-extension/extension/dependencies/DependencyManager.ts
  packages/blockchain-extension/extension/explorer/environmentExplorer.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/util/ExtensionsInteractionUtil.ts
  packages/blockchain-extension/test/commands/UserInputUtil.test.ts
  packages/blockchain-extension/test/dependencies/DependencyManager.test.ts
  packages/blockchain-extension/test/explorer/environmentExplorer.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-extension/test/util/ExtensionsInteractionUtil.test.ts
Labels: v2 pr

#2720 Updated v2 README
  README.md
Labels: v2 pr

#2721 [v2] - fix v2 tutorials
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a5.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a6.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a8.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a9.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/resources/listener.ts
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/resources/queryAllAssets.txt
Labels: v2 pr

#2739 [v2] - md2pdf in v2
  azure-pipelines.yml
  azure-templates/build-pdf.yml
Labels: v2 pr

#2740 [v2] - force pdf creation
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a9.md
Labels: v2 pr

#2742 [v2] - md2pdf in v2 - attempt 2
  azure-pipelines.yml
Labels: v2 pr

#2733 Add syntax highlighting using react-syntax-highlighter
  packages/blockchain-ui/enzyme/tests/TutorialSinglePage.test.tsx
  packages/blockchain-ui/enzyme/tests/__snapshots__/TutorialSinglePage.test.tsx.snap
  packages/blockchain-ui/package-lock.json
  packages/blockchain-ui/package.json
  packages/blockchain-ui/src/components/elements/TutorialMarkdown/TutorialMarkdown.tsx
Labels: v2 pr

#2745 [v2] - force pdf creation - take2
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a9.md
Labels: ignore-merge-2648, v2 pr

#2747 [v2] - force pdf creation - take3
  azure-templates/build-pdf.yml
Labels: ignore-merge-2648, v2 pr

#2749 [v2] - force pdf creation - take3
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a9.md
Labels: ignore-merge-2648, v2 pr

#2746 [merge-2648] - fix md2pdf
  azure-pipelines.yml
  azure-templates/build-pdf.yml
Labels: merge-2648 pr

#2752 Updated mergify config
  .mergify.yml
Labels: ignore-v2

#2759 [v2] - update tutorials with new images and text
  packages/blockchain-extension/ExtensionCommands.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a3.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a5.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a6.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a8.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a2.5.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a5.10.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a5.11.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a5.24.1.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a5.33.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a5.9.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a8.7.png
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-ui/enzyme/tests/TutorialSinglePage.test.tsx
  packages/blockchain-ui/enzyme/tests/__snapshots__/TutorialSinglePage.test.tsx.snap
  packages/blockchain-ui/src/components/elements/TutorialMarkdown/TutorialMarkdown.tsx
Labels: v2 pr

#2758 Edit path traversal for mdToPdf script
  packages/blockchain-extension/scripts/mdToPdf.sh
Labels: ignore-merge-2648, ignore-v2

#2738 [merge-2648] IBM Cloud Account changes + Node.js version
  README.md
  packages/blockchain-extension/ExtensionCommands.ts
  packages/blockchain-extension/extension/dependencies/Dependencies.ts
  packages/blockchain-extension/extension/dependencies/DependencyManager.ts
  packages/blockchain-extension/extension/explorer/environmentExplorer.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/extension/util/ExtensionsInteractionUtil.ts
  packages/blockchain-extension/extension/webview/PreReqView.ts
  packages/blockchain-extension/test/commands/UserInputUtil.test.ts
  packages/blockchain-extension/test/dependencies/DependencyManager.test.ts
  packages/blockchain-extension/test/explorer/environmentExplorer.test.ts
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-extension/test/util/ExtensionsInteractionUtil.test.ts
  packages/blockchain-extension/test/webview/PreReqView.test.ts
Labels: merge-2648 pr

#2761 [merge-2648] Add syntax highlighting using react-syntax-highlighter (Mergify/bp/merge 2648/pr 2733)
  packages/blockchain-ui/enzyme/tests/TutorialSinglePage.test.tsx
  packages/blockchain-ui/enzyme/tests/__snapshots__/TutorialSinglePage.test.tsx.snap
  packages/blockchain-ui/package-lock.json
  packages/blockchain-ui/package.json
  packages/blockchain-ui/src/components/elements/TutorialMarkdown/TutorialMarkdown.tsx
Labels: merge-2648 pr

#2771 [v1] remove azure pipeline run from mergify config
  .mergify.yml
Labels: ignore-v2

#2770 [v2] Updated a3 tutorial
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a3.md
Labels: v2 pr

#2772 [v2] Fix packaging metadata path
  packages/blockchain-environment-v1/test/PackageSmartContract.test.ts
  packages/blockchain-extension/extension/commands/packageSmartContractCommand.ts
  packages/blockchain-extension/test/commands/packageSmartContractCommand.test.ts
Labels: v2 pr

#2769 [merge-2648] - update tutorials with new images and text (#2759)
  packages/blockchain-extension/ExtensionCommands.ts
  packages/blockchain-extension/extension/util/ExtensionUtil.ts
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a3.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a5.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a6.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/a8.md
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a2.5.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a5.10.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a5.11.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a5.24.1.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a5.33.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a5.9.png
  packages/blockchain-extension/resources/tutorials/new-tutorials/basic-tutorials/images/a8.7.png
  packages/blockchain-extension/test/util/ExtensionUtil.test.ts
  packages/blockchain-ui/enzyme/tests/TutorialSinglePage.test.tsx
  packages/blockchain-ui/enzyme/tests/__snapshots__/TutorialSinglePage.test.tsx.snap
  packages/blockchain-ui/src/components/elements/TutorialMarkdown/TutorialMarkdown.tsx
Labels: merge-2648 pr

#2777 Changelog (v2)
  CHANGELOG.md
  packages/blockchain-extension/RELEASE-NOTES.md
Labels: v2 pr

#2776 Changelog
  CHANGELOG.md
  packages/blockchain-extension/RELEASE-NOTES.md
Labels: ignore-v2
